### ISSUE TITLE
Days not in calendar format  

### ISSUE THREAD

**Issue by DavidSSchwartz** [Adphorus/react-date-range#220] opened 2018-07-12 08:29 UTC
## Subject of the issue
Describe your issue here.
I have no idea how this happened.  I changed the place of the component in my app and all the numbers got screwed up.
Here's  a screenshot.
what could be the problem?

![screen shot 2018-07-12 at 11 27 46](https://user-images.githubusercontent.com/26358131/42621551-ce6705a2-85c6-11e8-849c-9fcc8215c70f.png)
[](url)
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

## Environment
Package Version:
React version:
Node version:
Browser:

**Comment by mkg0** [comment] 2018-07-12 09:38
hi @DavidSSchwartz 

Probably it's because of the parent element's display property inheritance.
Can you create a minimal repo to reproduce this issue?

**Comment by DavidSSchwartz** [comment] 2018-07-12 09:59
thanks! just figured it out
It was inheriting "white-space: no-wrap"

**Comment by mkg0** [comment] 2018-07-12 10:00
great!
Then I'm closing this 🙂

**Closed by mkg0** 2018-07-12 10:00 UTC
